---
title: "Analysing candidates to the Chamber of Deputies throughout the elections"
author: "Bogdan Romenskii"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
 html_document:
  df_print: paged
  code_folding: show
  toc: yes
  toc_float: yes
  toc_depth: 3
  theme: readable
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width = 6, fig.height = 4)
```
```{r}
library(plyr) # mapvalues function
library(tidyverse)
library(jsonlite)
library(glue) # for python f-string analogue
```

### Data uploading and preprocessing
```{r auxillary files}
kraj_list <- c("Hlavní město Praha", "Středočeský kraj", "Jihočeský kraj", "Plzeňský kraj", "Karlovarský kraj",
               "Ústecký kraj", "Liberecký kraj", "Královéhradecký kraj", "Pardubický kraj", "Kraj Vysočina",
               "Jihomoravský kraj", "Olomoucký kraj", "Zlínský kraj", "Moravskoslezský kraj")

strany <- read_csv2("../legislative-elections/strany.csv",
                    locale = locale(encoding = "UTF-8"))

obor_json <- fromJSON("../dict_occupations.json")
```

```{r obor_fun}
obor_fun <- function(val, dict){
  for(i in seq_along(dict)){
    for(j in seq_along(dict[[i]]$var)){
      if(grepl(dict[[i]]$var[j], tolower(val), fixed = TRUE)){
        return(dict[[i]]$name)
      }
    }
  }
  return("jine")
}
```

```{r clean_data function}
clean_data <- function(df){
  df1 <- df %>%
    # creates a new column with name and surname as one
    mutate(cele_jmeno = paste(JMENO, PRIJMENI, sep = " "),
           # checks whether the candidate has any titles, if so - university degree is set to 1
           vs_vzdelani = if_else(
             !is.na(TITULPRED) | !is.na(TITULZA), 1, 0
           ),
           # maps regions' names
           kraj = mapvalues(VOLKRAJ, 1:14, kraj_list),
           # transforms mandate to standard form
           mandat = if_else(
             MANDAT == "A" | MANDAT == "1", 1, 0
           ),
           # obor_fun function is applied on a POVOLANI column, unlists is used twice after that
           obor = unlist(
             unlist(
               lapply(df$POVOLANI, function(x) lapply(x, obor_fun, obor_json)),
               recursive = FALSE),
             recursive = FALSE)) %>%
    # creates gender column based on surname ending
    mutate(pohlavi = if_else(
      substr(cele_jmeno, nchar(cele_jmeno), nchar(cele_jmeno)) == "á", "F", "M"
    )) %>%
    # joins another table to map candidates' ideology based on their party
    left_join(strany %>%
                select(VSTRANA, Ideologie),
              by = c("NSTRANA" = "VSTRANA")) %>%
    # selects only relevant columns
    select(cele_jmeno, VEK, vs_vzdelani, obor, pohlavi, kraj, Ideologie, mandat) %>%
    # renames some of the columns to match the standard format
    rename("vek" = "VEK",
           "ideologie" = "Ideologie") %>%
    # changes data types to factors in the according columns
    mutate(vs_vzdelani = factor(vs_vzdelani),
           obor = factor(obor),
           pohlavi = factor(pohlavi),
           kraj = factor(kraj),
           ideologie = factor(ideologie),
           mandat = factor(mandat))

  return(df1)
}
```

```{r csv uploads, message = FALSE}
snem_list <- list()
years <- c("2006", "2010", "2013", "2017", "2021")

for(i in seq_along(years)){
  year <- years[i]
  snem_list[[i]] <- clean_data(
    read_csv2(glue("legislative-elections/snem_{year}.csv"),
                              locale = locale(encoding = "UTF-8"))
  )
  snem_list[[i]]$year <- year
}

head(snem_list[[1]])
```

```{r concatenating the list}
snem_long <- rbind.fill(snem_list) %>%
  mutate(year = factor(year))

head(snem_long)
```
```{r glimpse}
glimpse(snem_long)
```
```{r NAs}
colSums(is.na(snem_long))
table(snem_long$ideologie)
```
```{r}
snem_long %>%
        filter(is.na(vek))
```
```{r}
snem_long <- snem_long %>%
        # deleting the dummy NA rows
        filter(!is.na(vek)) %>%
        # implying the majority group into NA values
        replace_na(list(ideologie = as.factor("Pravice")))

glimpse(snem_long)
```
```{r}
colSums(is.na(snem_long))
```
### Exploratory Data Analysis
```{r}
ggplot(snem_long, aes(vek)) +
        geom_density(aes(colour = pohlavi, fill = pohlavi), alpha = 0.1) +
        facet_wrap(vars(year))
```
```{r}
table(snem_long$pohlavi)
```
